import { MigrationInterface, QueryRunner } from "typeorm";

export class RenameEmailCodes1750899306034 implements MigrationInterface {
    name = 'RenameEmailCodes1750899306034'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`FK_f6c3223e06f14dd26279cf9824c\` ON \`game_inning_stats\``);
        await queryRunner.query(`DROP INDEX \`FK_a17ef1eb8f0819d11d7a33662ff\` ON \`games\``);
        await queryRunner.query(`DROP INDEX \`FK_fb2fabf4d3e0529d229b3d215d4\` ON \`games\``);
        await queryRunner.query(`DROP INDEX \`FK_472b25323af01488f1f66a06b67\` ON \`user_roles\``);
        await queryRunner.query(`DROP INDEX \`FK_6cbe4519348a1cf7f5798c76525\` ON \`user_roles\``);
        await queryRunner.query(`DROP INDEX \`FK_7f19e23d839055607fa6761d536\` ON \`user_roles\``);
        await queryRunner.query(`DROP INDEX \`FK_32fd16272efc8c74fbf33073703\` ON \`player_entries\``);
        await queryRunner.query(`DROP INDEX \`FK_f682ad4cc670ad6c58f11193b2d\` ON \`player_entries\``);
        await queryRunner.query(`DROP INDEX \`FK_6ece045c0e2580a01b93e242ffa\` ON \`umpire_entries\``);
        await queryRunner.query(`DROP INDEX \`FK_8a10e5f29e4a6522b6649e6d472\` ON \`umpire_entries\``);
        await queryRunner.query(`DROP INDEX \`FK_0921d1972cf861d568f5271cd85\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`FK_469924aa829cfae9274cdd8edbc\` ON \`user_profiles\``);
        await queryRunner.query(`DROP INDEX \`FK_bea893a3db3448a304ab6d729f3\` ON \`user_profiles\``);
        await queryRunner.query(`DROP INDEX \`FK_031d56f4b0c9492b176cc29d07c\` ON \`departments\``);
        await queryRunner.query(`DROP INDEX \`FK_57de40bc620f456c7311aa3a1e6\` ON \`sessions\``);
        await queryRunner.query(`CREATE TABLE \`email_codes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`email\` varchar(150) NOT NULL, \`code_hash\` varchar(255) NOT NULL, \`expires_at\` timestamp NULL, \`verified_at\` timestamp NULL, \`try_count\` int NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, UNIQUE INDEX \`IDX_7f04654f5cfac4e12854449754\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`player_entries\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`player_entries\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`player_entries\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`player_entries\` ADD \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`umpire_entries\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`umpire_entries\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`umpire_entries\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`umpire_entries\` ADD \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`passwordHash\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`passwordHash\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sessions\` DROP COLUMN \`tokenHash\``);
        await queryRunner.query(`ALTER TABLE \`sessions\` ADD \`tokenHash\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`game_inning_stats\` ADD CONSTRAINT \`FK_f6c3223e06f14dd26279cf9824c\` FOREIGN KEY (\`game_id\`) REFERENCES \`games\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`batter_game_stats\` ADD CONSTRAINT \`FK_3bd2cb3f2b7140f750a0fdaac8d\` FOREIGN KEY (\`batter_game_participation_id\`) REFERENCES \`batter_game_participations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` ADD CONSTRAINT \`FK_b29689d47b22e01defb6efd7af3\` FOREIGN KEY (\`game_id\`) REFERENCES \`games\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` ADD CONSTRAINT \`FK_a7ccc1dd62d56aac8100c4c6ba6\` FOREIGN KEY (\`team_id\`) REFERENCES \`teams\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` ADD CONSTRAINT \`FK_cf2b31d93d5f27d5c7545cf4781\` FOREIGN KEY (\`player_id\`) REFERENCES \`players\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_stats\` ADD CONSTRAINT \`FK_36c2e15af9df5e963ca0ae2135e\` FOREIGN KEY (\`pitcher_game_participation_id\`) REFERENCES \`pitcher_game_participations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` ADD CONSTRAINT \`FK_183a7e71b8769c92691056c67b2\` FOREIGN KEY (\`game_id\`) REFERENCES \`games\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` ADD CONSTRAINT \`FK_61a0c2f525649b1e1772df22bb2\` FOREIGN KEY (\`team_id\`) REFERENCES \`teams\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` ADD CONSTRAINT \`FK_1b51def7742927b8eb23efe38b7\` FOREIGN KEY (\`player_id\`) REFERENCES \`players\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_stats\` ADD CONSTRAINT \`FK_a8e2b0df27f8baa40c5aef8d3e3\` FOREIGN KEY (\`game_id\`) REFERENCES \`games\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_stats\` ADD CONSTRAINT \`FK_bd5db571ec09d387d82d84daf3d\` FOREIGN KEY (\`home_pitcher_participation_id\`) REFERENCES \`pitcher_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_stats\` ADD CONSTRAINT \`FK_207a04127d611441d47686ceeb5\` FOREIGN KEY (\`home_batter_participation_id\`) REFERENCES \`batter_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_stats\` ADD CONSTRAINT \`FK_13a674c8d1715401b040983dee8\` FOREIGN KEY (\`away_pitcher_participation_id\`) REFERENCES \`pitcher_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_stats\` ADD CONSTRAINT \`FK_73309278f6c6b7b7a273c240567\` FOREIGN KEY (\`away_batter_participation_id\`) REFERENCES \`batter_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` ADD CONSTRAINT \`FK_f55dcf4120348b21aa899a00822\` FOREIGN KEY (\`game_id\`) REFERENCES \`games\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` ADD CONSTRAINT \`FK_0ab4fa69ea5db41cf49ccbb9d2a\` FOREIGN KEY (\`team_id\`) REFERENCES \`teams\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` ADD CONSTRAINT \`FK_ca7cbf0f39d4505f3def4ee2198\` FOREIGN KEY (\`player_id\`) REFERENCES \`players\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_231e3bf4d40e033e03864137113\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`tournaments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_f6bc2302c5abcb1237f534d6efc\` FOREIGN KEY (\`home_team_id\`) REFERENCES \`teams\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_fbe84ca8c9405ed07bf7d471883\` FOREIGN KEY (\`away_team_id\`) REFERENCES \`teams\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_a17ef1eb8f0819d11d7a33662ff\` FOREIGN KEY (\`winner_team_id\`) REFERENCES \`teams\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_fb2fabf4d3e0529d229b3d215d4\` FOREIGN KEY (\`record_umpire_id\`) REFERENCES \`umpires\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`umpires\` ADD CONSTRAINT \`FK_fd8afb174c95560b417d1230136\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`umpire_tournaments\` ADD CONSTRAINT \`FK_ba4b70070b8d5110132f35de419\` FOREIGN KEY (\`umpire_id\`) REFERENCES \`umpires\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`umpire_tournaments\` ADD CONSTRAINT \`FK_567c84be6fc109ed6426e8f6384\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_472b25323af01488f1f66a06b67\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_6cbe4519348a1cf7f5798c76525\` FOREIGN KEY (\`tournamentId\`) REFERENCES \`tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_7f19e23d839055607fa6761d536\` FOREIGN KEY (\`teamTournamentId\`) REFERENCES \`team_tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` ADD CONSTRAINT \`FK_c0525e576c026928aec2fb95bb5\` FOREIGN KEY (\`player_id\`) REFERENCES \`players\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` ADD CONSTRAINT \`FK_d3f70e4ffdd3b0bcfb957439b6e\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`players\` ADD CONSTRAINT \`FK_ce457a554d63e92f4627d6c5763\` FOREIGN KEY (\`team_id\`) REFERENCES \`teams\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team_tournaments\` ADD CONSTRAINT \`FK_f95b4d911f29f91a7df914f7cf5\` FOREIGN KEY (\`team_id\`) REFERENCES \`teams\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team_tournaments\` ADD CONSTRAINT \`FK_0843a2f852f36e58beff26c7087\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player_entries\` ADD CONSTRAINT \`FK_f682ad4cc670ad6c58f11193b2d\` FOREIGN KEY (\`team_tournament_id\`) REFERENCES \`team_tournaments\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player_entries\` ADD CONSTRAINT \`FK_32fd16272efc8c74fbf33073703\` FOREIGN KEY (\`claimUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`umpire_entries\` ADD CONSTRAINT \`FK_8a10e5f29e4a6522b6649e6d472\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`tournaments\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`umpire_entries\` ADD CONSTRAINT \`FK_6ece045c0e2580a01b93e242ffa\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_0921d1972cf861d568f5271cd85\` FOREIGN KEY (\`department_id\`) REFERENCES \`departments\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_profiles\` ADD CONSTRAINT \`FK_8481388d6325e752cd4d7e26c6d\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_profiles\` ADD CONSTRAINT \`FK_bea893a3db3448a304ab6d729f3\` FOREIGN KEY (\`collegeId\`) REFERENCES \`colleges\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_profiles\` ADD CONSTRAINT \`FK_469924aa829cfae9274cdd8edbc\` FOREIGN KEY (\`departmentId\`) REFERENCES \`departments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD CONSTRAINT \`FK_031d56f4b0c9492b176cc29d07c\` FOREIGN KEY (\`collegeId\`) REFERENCES \`colleges\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batter_stats\` ADD CONSTRAINT \`FK_673bbc97c1577000b37840d4e1e\` FOREIGN KEY (\`player_tournament_id\`) REFERENCES \`player_tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pitcher_stats\` ADD CONSTRAINT \`FK_44266091b556e03d241ace53da0\` FOREIGN KEY (\`player_tournament_id\`) REFERENCES \`player_tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sessions\` ADD CONSTRAINT \`FK_57de40bc620f456c7311aa3a1e6\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`sessions\` DROP FOREIGN KEY \`FK_57de40bc620f456c7311aa3a1e6\``);
        await queryRunner.query(`ALTER TABLE \`pitcher_stats\` DROP FOREIGN KEY \`FK_44266091b556e03d241ace53da0\``);
        await queryRunner.query(`ALTER TABLE \`batter_stats\` DROP FOREIGN KEY \`FK_673bbc97c1577000b37840d4e1e\``);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP FOREIGN KEY \`FK_031d56f4b0c9492b176cc29d07c\``);
        await queryRunner.query(`ALTER TABLE \`user_profiles\` DROP FOREIGN KEY \`FK_469924aa829cfae9274cdd8edbc\``);
        await queryRunner.query(`ALTER TABLE \`user_profiles\` DROP FOREIGN KEY \`FK_bea893a3db3448a304ab6d729f3\``);
        await queryRunner.query(`ALTER TABLE \`user_profiles\` DROP FOREIGN KEY \`FK_8481388d6325e752cd4d7e26c6d\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_0921d1972cf861d568f5271cd85\``);
        await queryRunner.query(`ALTER TABLE \`umpire_entries\` DROP FOREIGN KEY \`FK_6ece045c0e2580a01b93e242ffa\``);
        await queryRunner.query(`ALTER TABLE \`umpire_entries\` DROP FOREIGN KEY \`FK_8a10e5f29e4a6522b6649e6d472\``);
        await queryRunner.query(`ALTER TABLE \`player_entries\` DROP FOREIGN KEY \`FK_32fd16272efc8c74fbf33073703\``);
        await queryRunner.query(`ALTER TABLE \`player_entries\` DROP FOREIGN KEY \`FK_f682ad4cc670ad6c58f11193b2d\``);
        await queryRunner.query(`ALTER TABLE \`team_tournaments\` DROP FOREIGN KEY \`FK_0843a2f852f36e58beff26c7087\``);
        await queryRunner.query(`ALTER TABLE \`team_tournaments\` DROP FOREIGN KEY \`FK_f95b4d911f29f91a7df914f7cf5\``);
        await queryRunner.query(`ALTER TABLE \`players\` DROP FOREIGN KEY \`FK_ce457a554d63e92f4627d6c5763\``);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` DROP FOREIGN KEY \`FK_d3f70e4ffdd3b0bcfb957439b6e\``);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` DROP FOREIGN KEY \`FK_c0525e576c026928aec2fb95bb5\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_7f19e23d839055607fa6761d536\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_6cbe4519348a1cf7f5798c76525\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_472b25323af01488f1f66a06b67\``);
        await queryRunner.query(`ALTER TABLE \`umpire_tournaments\` DROP FOREIGN KEY \`FK_567c84be6fc109ed6426e8f6384\``);
        await queryRunner.query(`ALTER TABLE \`umpire_tournaments\` DROP FOREIGN KEY \`FK_ba4b70070b8d5110132f35de419\``);
        await queryRunner.query(`ALTER TABLE \`umpires\` DROP FOREIGN KEY \`FK_fd8afb174c95560b417d1230136\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_fb2fabf4d3e0529d229b3d215d4\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_a17ef1eb8f0819d11d7a33662ff\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_fbe84ca8c9405ed07bf7d471883\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_f6bc2302c5abcb1237f534d6efc\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_231e3bf4d40e033e03864137113\``);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` DROP FOREIGN KEY \`FK_ca7cbf0f39d4505f3def4ee2198\``);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` DROP FOREIGN KEY \`FK_0ab4fa69ea5db41cf49ccbb9d2a\``);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` DROP FOREIGN KEY \`FK_f55dcf4120348b21aa899a00822\``);
        await queryRunner.query(`ALTER TABLE \`game_stats\` DROP FOREIGN KEY \`FK_73309278f6c6b7b7a273c240567\``);
        await queryRunner.query(`ALTER TABLE \`game_stats\` DROP FOREIGN KEY \`FK_13a674c8d1715401b040983dee8\``);
        await queryRunner.query(`ALTER TABLE \`game_stats\` DROP FOREIGN KEY \`FK_207a04127d611441d47686ceeb5\``);
        await queryRunner.query(`ALTER TABLE \`game_stats\` DROP FOREIGN KEY \`FK_bd5db571ec09d387d82d84daf3d\``);
        await queryRunner.query(`ALTER TABLE \`game_stats\` DROP FOREIGN KEY \`FK_a8e2b0df27f8baa40c5aef8d3e3\``);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` DROP FOREIGN KEY \`FK_1b51def7742927b8eb23efe38b7\``);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` DROP FOREIGN KEY \`FK_61a0c2f525649b1e1772df22bb2\``);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` DROP FOREIGN KEY \`FK_183a7e71b8769c92691056c67b2\``);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_stats\` DROP FOREIGN KEY \`FK_36c2e15af9df5e963ca0ae2135e\``);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` DROP FOREIGN KEY \`FK_cf2b31d93d5f27d5c7545cf4781\``);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` DROP FOREIGN KEY \`FK_a7ccc1dd62d56aac8100c4c6ba6\``);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` DROP FOREIGN KEY \`FK_b29689d47b22e01defb6efd7af3\``);
        await queryRunner.query(`ALTER TABLE \`batter_game_stats\` DROP FOREIGN KEY \`FK_3bd2cb3f2b7140f750a0fdaac8d\``);
        await queryRunner.query(`ALTER TABLE \`game_inning_stats\` DROP FOREIGN KEY \`FK_f6c3223e06f14dd26279cf9824c\``);
        await queryRunner.query(`ALTER TABLE \`sessions\` DROP COLUMN \`tokenHash\``);
        await queryRunner.query(`ALTER TABLE \`sessions\` ADD \`tokenHash\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`passwordHash\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`passwordHash\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`umpire_entries\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`umpire_entries\` ADD \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`umpire_entries\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`umpire_entries\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`player_entries\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`player_entries\` ADD \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`player_entries\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`player_entries\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_7f04654f5cfac4e12854449754\` ON \`email_codes\``);
        await queryRunner.query(`DROP TABLE \`email_codes\``);
        await queryRunner.query(`CREATE INDEX \`FK_57de40bc620f456c7311aa3a1e6\` ON \`sessions\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_031d56f4b0c9492b176cc29d07c\` ON \`departments\` (\`collegeId\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_bea893a3db3448a304ab6d729f3\` ON \`user_profiles\` (\`collegeId\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_469924aa829cfae9274cdd8edbc\` ON \`user_profiles\` (\`departmentId\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_0921d1972cf861d568f5271cd85\` ON \`users\` (\`department_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_8a10e5f29e4a6522b6649e6d472\` ON \`umpire_entries\` (\`tournament_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_6ece045c0e2580a01b93e242ffa\` ON \`umpire_entries\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_f682ad4cc670ad6c58f11193b2d\` ON \`player_entries\` (\`team_tournament_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_32fd16272efc8c74fbf33073703\` ON \`player_entries\` (\`claimUserId\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_7f19e23d839055607fa6761d536\` ON \`user_roles\` (\`teamTournamentId\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_6cbe4519348a1cf7f5798c76525\` ON \`user_roles\` (\`tournamentId\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_472b25323af01488f1f66a06b67\` ON \`user_roles\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_fb2fabf4d3e0529d229b3d215d4\` ON \`games\` (\`record_umpire_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_a17ef1eb8f0819d11d7a33662ff\` ON \`games\` (\`winner_team_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_f6c3223e06f14dd26279cf9824c\` ON \`game_inning_stats\` (\`game_id\`)`);
    }

}
