import { MigrationInterface, QueryRunner } from "typeorm";

export class ChangeTeamIdToTeamTournamentId1754002875683 implements MigrationInterface {
    name = 'ChangeTeamIdToTeamTournamentId1754002875683'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_profiles\` DROP FOREIGN KEY \`FK_8481388d6325e752cd4d7e26c6d\``);
        await queryRunner.query(`ALTER TABLE \`game_inning_stats\` DROP FOREIGN KEY \`FK_f6c3223e06f14dd26279cf9824c\``);
        await queryRunner.query(`ALTER TABLE \`virtual_inning_stats\` DROP FOREIGN KEY \`FK_bcb6efe098d74ce92775eb8c9f0\``);
        await queryRunner.query(`ALTER TABLE \`batter_game_stats\` DROP FOREIGN KEY \`FK_3bd2cb3f2b7140f750a0fdaac8d\``);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` DROP FOREIGN KEY \`FK_a7ccc1dd62d56aac8100c4c6ba6\``);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` DROP FOREIGN KEY \`FK_b29689d47b22e01defb6efd7af3\``);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` DROP FOREIGN KEY \`FK_f247f29600c4a080125d454072b\``);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_stats\` DROP FOREIGN KEY \`FK_36c2e15af9df5e963ca0ae2135e\``);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` DROP FOREIGN KEY \`FK_183a7e71b8769c92691056c67b2\``);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` DROP FOREIGN KEY \`FK_61a0c2f525649b1e1772df22bb2\``);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` DROP FOREIGN KEY \`FK_b1dab303eb41058aff75ce26ace\``);
        await queryRunner.query(`ALTER TABLE \`game_stats\` DROP FOREIGN KEY \`FK_13a674c8d1715401b040983dee8\``);
        await queryRunner.query(`ALTER TABLE \`game_stats\` DROP FOREIGN KEY \`FK_207a04127d611441d47686ceeb5\``);
        await queryRunner.query(`ALTER TABLE \`game_stats\` DROP FOREIGN KEY \`FK_73309278f6c6b7b7a273c240567\``);
        await queryRunner.query(`ALTER TABLE \`game_stats\` DROP FOREIGN KEY \`FK_a8e2b0df27f8baa40c5aef8d3e3\``);
        await queryRunner.query(`ALTER TABLE \`game_stats\` DROP FOREIGN KEY \`FK_bd5db571ec09d387d82d84daf3d\``);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` DROP FOREIGN KEY \`FK_0ab4fa69ea5db41cf49ccbb9d2a\``);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` DROP FOREIGN KEY \`FK_d40a0d4af3721b583167fdeef3c\``);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` DROP FOREIGN KEY \`FK_f55dcf4120348b21aa899a00822\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_231e3bf4d40e033e03864137113\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_7320d78e74745e16633ec876b06\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_9b58bea27187d8b7eb0888ac40f\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_cb2180da34b81b7fd5a44a4e06a\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_fb2fabf4d3e0529d229b3d215d4\``);
        await queryRunner.query(`ALTER TABLE \`umpires\` DROP FOREIGN KEY \`FK_fd8afb174c95560b417d1230136\``);
        await queryRunner.query(`ALTER TABLE \`umpire_tournaments\` DROP FOREIGN KEY \`FK_567c84be6fc109ed6426e8f6384\``);
        await queryRunner.query(`ALTER TABLE \`umpire_tournaments\` DROP FOREIGN KEY \`FK_ba4b70070b8d5110132f35de419\``);
        await queryRunner.query(`ALTER TABLE \`team_tournaments\` DROP FOREIGN KEY \`FK_0843a2f852f36e58beff26c7087\``);
        await queryRunner.query(`ALTER TABLE \`team_tournaments\` DROP FOREIGN KEY \`FK_f95b4d911f29f91a7df914f7cf5\``);
        await queryRunner.query(`ALTER TABLE \`team_tournaments\` DROP FOREIGN KEY \`FK_ffc945523d3efda71a653a9e261\``);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` DROP FOREIGN KEY \`FK_2e9fe9ad3545c10f0e68b23e67a\``);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` DROP FOREIGN KEY \`FK_4affd1bc756929948778a93a645\``);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` DROP FOREIGN KEY \`FK_c0525e576c026928aec2fb95bb5\``);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP FOREIGN KEY \`FK_031d56f4b0c9492b176cc29d07c\``);
        await queryRunner.query(`ALTER TABLE \`players\` DROP FOREIGN KEY \`FK_a88b3d61091c2a3504e19e616fa\``);
        await queryRunner.query(`ALTER TABLE \`players\` DROP FOREIGN KEY \`FK_ba3575d2fbe71fab7155366235e\``);
        await queryRunner.query(`ALTER TABLE \`players\` DROP FOREIGN KEY \`FK_d95435c3de3a663682fa21ebc23\``);
        await queryRunner.query(`ALTER TABLE \`batter_stats\` DROP FOREIGN KEY \`FK_673bbc97c1577000b37840d4e1e\``);
        await queryRunner.query(`ALTER TABLE \`pitcher_stats\` DROP FOREIGN KEY \`FK_44266091b556e03d241ace53da0\``);
        await queryRunner.query(`ALTER TABLE \`sessions\` DROP FOREIGN KEY \`FK_57de40bc620f456c7311aa3a1e6\``);
        await queryRunner.query(`ALTER TABLE \`runner_events\` DROP FOREIGN KEY \`FK_29ed21b50d29b0627d007fbac6c\``);
        await queryRunner.query(`ALTER TABLE \`runner_events\` DROP FOREIGN KEY \`FK_59adfc26d4958ba0a1f8bd08849\``);
        await queryRunner.query(`ALTER TABLE \`runner_events\` DROP FOREIGN KEY \`FK_767c5bc5e6b54b9ad7b7569526a\``);
        await queryRunner.query(`ALTER TABLE \`runner_events\` DROP FOREIGN KEY \`FK_b31c667c86e6af25392aeb7bbb6\``);
        await queryRunner.query(`ALTER TABLE \`plays\` DROP FOREIGN KEY \`FK_05ecc278ef6219afcf59347a543\``);
        await queryRunner.query(`ALTER TABLE \`plays\` DROP FOREIGN KEY \`FK_8bedafb77b3b33f233e5cfde092\``);
        await queryRunner.query(`ALTER TABLE \`plays\` DROP FOREIGN KEY \`FK_ee54c0bd8cc99751aa38be798b4\``);
        await queryRunner.query(`ALTER TABLE \`plays\` DROP FOREIGN KEY \`FK_f447505ff7bf84e808b302d1ce7\``);
        await queryRunner.query(`ALTER TABLE \`runner\` DROP FOREIGN KEY \`FK_137287a68699d56d7c2ab369daa\``);
        await queryRunner.query(`ALTER TABLE \`runner\` DROP FOREIGN KEY \`FK_58e3b2068aaa4d74ec081daec3e\``);
        await queryRunner.query(`ALTER TABLE \`runner\` DROP FOREIGN KEY \`FK_8b9c7b05d9891ebd54e07703b87\``);
        await queryRunner.query(`DROP INDEX \`IDX_a7ccc1dd62d56aac8100c4c6ba\` ON \`batter_game_participations\``);
        await queryRunner.query(`DROP INDEX \`IDX_61a0c2f525649b1e1772df22bb\` ON \`pitcher_game_participations\``);
        await queryRunner.query(`DROP INDEX \`IDX_0ab4fa69ea5db41cf49ccbb9d2\` ON \`game_roasters\``);
        await queryRunner.query(`DROP INDEX \`IDX_e087b4110e44a0d42a4c8a3749\` ON \`game_roasters\``);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` CHANGE \`team_id\` \`team_tournament_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` CHANGE \`team_id\` \`team_tournament_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` CHANGE \`team_id\` \`team_tournament_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` DROP COLUMN \`backNumber\``);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` ADD \`backNumber\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`email_codes\` DROP COLUMN \`code_hash\``);
        await queryRunner.query(`ALTER TABLE \`email_codes\` ADD \`code_hash\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`password_reset_tokens\` DROP COLUMN \`token_hash\``);
        await queryRunner.query(`ALTER TABLE \`password_reset_tokens\` ADD \`token_hash\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`runner_events\` DROP COLUMN \`start_base\``);
        await queryRunner.query(`ALTER TABLE \`runner_events\` ADD \`start_base\` char(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`runner_events\` DROP COLUMN \`end_base\``);
        await queryRunner.query(`ALTER TABLE \`runner_events\` ADD \`end_base\` char(1) NOT NULL`);
        await queryRunner.query(`CREATE INDEX \`IDX_16148e5132d3068b00ade5c782\` ON \`batter_game_participations\` (\`team_tournament_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_61a70554b6791a1021a1c80594\` ON \`pitcher_game_participations\` (\`team_tournament_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_19742fdd1e5d7b047078be2318\` ON \`game_roasters\` (\`team_tournament_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_f5ab3feef948b23b5ab100becd\` ON \`game_roasters\` (\`game_id\`, \`team_tournament_id\`, \`player_tournament_id\`)`);
        await queryRunner.query(`ALTER TABLE \`user_profiles\` ADD CONSTRAINT \`FK_8481388d6325e752cd4d7e26c6d\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_inning_stats\` ADD CONSTRAINT \`FK_f6c3223e06f14dd26279cf9824c\` FOREIGN KEY (\`game_id\`) REFERENCES \`games\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`virtual_inning_stats\` ADD CONSTRAINT \`FK_bcb6efe098d74ce92775eb8c9f0\` FOREIGN KEY (\`game_id\`) REFERENCES \`games\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`batter_game_stats\` ADD CONSTRAINT \`FK_3bd2cb3f2b7140f750a0fdaac8d\` FOREIGN KEY (\`batter_game_participation_id\`) REFERENCES \`batter_game_participations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` ADD CONSTRAINT \`FK_b29689d47b22e01defb6efd7af3\` FOREIGN KEY (\`game_id\`) REFERENCES \`games\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` ADD CONSTRAINT \`FK_16148e5132d3068b00ade5c7827\` FOREIGN KEY (\`team_tournament_id\`) REFERENCES \`team_tournaments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` ADD CONSTRAINT \`FK_f247f29600c4a080125d454072b\` FOREIGN KEY (\`player_tournament_id\`) REFERENCES \`player_tournaments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_stats\` ADD CONSTRAINT \`FK_36c2e15af9df5e963ca0ae2135e\` FOREIGN KEY (\`pitcher_game_participation_id\`) REFERENCES \`pitcher_game_participations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` ADD CONSTRAINT \`FK_183a7e71b8769c92691056c67b2\` FOREIGN KEY (\`game_id\`) REFERENCES \`games\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` ADD CONSTRAINT \`FK_61a70554b6791a1021a1c80594f\` FOREIGN KEY (\`team_tournament_id\`) REFERENCES \`team_tournaments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` ADD CONSTRAINT \`FK_b1dab303eb41058aff75ce26ace\` FOREIGN KEY (\`player_tournament_id\`) REFERENCES \`player_tournaments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_stats\` ADD CONSTRAINT \`FK_a8e2b0df27f8baa40c5aef8d3e3\` FOREIGN KEY (\`game_id\`) REFERENCES \`games\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_stats\` ADD CONSTRAINT \`FK_bd5db571ec09d387d82d84daf3d\` FOREIGN KEY (\`home_pitcher_participation_id\`) REFERENCES \`pitcher_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_stats\` ADD CONSTRAINT \`FK_207a04127d611441d47686ceeb5\` FOREIGN KEY (\`home_batter_participation_id\`) REFERENCES \`batter_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_stats\` ADD CONSTRAINT \`FK_13a674c8d1715401b040983dee8\` FOREIGN KEY (\`away_pitcher_participation_id\`) REFERENCES \`pitcher_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_stats\` ADD CONSTRAINT \`FK_73309278f6c6b7b7a273c240567\` FOREIGN KEY (\`away_batter_participation_id\`) REFERENCES \`batter_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` ADD CONSTRAINT \`FK_f55dcf4120348b21aa899a00822\` FOREIGN KEY (\`game_id\`) REFERENCES \`games\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` ADD CONSTRAINT \`FK_19742fdd1e5d7b047078be23181\` FOREIGN KEY (\`team_tournament_id\`) REFERENCES \`team_tournaments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` ADD CONSTRAINT \`FK_d40a0d4af3721b583167fdeef3c\` FOREIGN KEY (\`player_tournament_id\`) REFERENCES \`player_tournaments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_231e3bf4d40e033e03864137113\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`tournaments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_7320d78e74745e16633ec876b06\` FOREIGN KEY (\`home_team_tournament_id\`) REFERENCES \`team_tournaments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_cb2180da34b81b7fd5a44a4e06a\` FOREIGN KEY (\`away_team_tournament_id\`) REFERENCES \`team_tournaments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_9b58bea27187d8b7eb0888ac40f\` FOREIGN KEY (\`winner_team_tournament_id\`) REFERENCES \`team_tournaments\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_fb2fabf4d3e0529d229b3d215d4\` FOREIGN KEY (\`record_umpire_id\`) REFERENCES \`umpires\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`umpires\` ADD CONSTRAINT \`FK_fd8afb174c95560b417d1230136\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`umpire_tournaments\` ADD CONSTRAINT \`FK_ba4b70070b8d5110132f35de419\` FOREIGN KEY (\`umpire_id\`) REFERENCES \`umpires\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`umpire_tournaments\` ADD CONSTRAINT \`FK_567c84be6fc109ed6426e8f6384\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team_tournaments\` ADD CONSTRAINT \`FK_f95b4d911f29f91a7df914f7cf5\` FOREIGN KEY (\`team_id\`) REFERENCES \`teams\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team_tournaments\` ADD CONSTRAINT \`FK_0843a2f852f36e58beff26c7087\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team_tournaments\` ADD CONSTRAINT \`FK_ffc945523d3efda71a653a9e261\` FOREIGN KEY (\`representative_user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` ADD CONSTRAINT \`FK_c0525e576c026928aec2fb95bb5\` FOREIGN KEY (\`player_id\`) REFERENCES \`players\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` ADD CONSTRAINT \`FK_2e9fe9ad3545c10f0e68b23e67a\` FOREIGN KEY (\`team_tournament_id\`) REFERENCES \`team_tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` ADD CONSTRAINT \`FK_4affd1bc756929948778a93a645\` FOREIGN KEY (\`claim_user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD CONSTRAINT \`FK_031d56f4b0c9492b176cc29d07c\` FOREIGN KEY (\`collegeId\`) REFERENCES \`colleges\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`players\` ADD CONSTRAINT \`FK_ba3575d2fbe71fab7155366235e\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`players\` ADD CONSTRAINT \`FK_a88b3d61091c2a3504e19e616fa\` FOREIGN KEY (\`college_id\`) REFERENCES \`colleges\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`players\` ADD CONSTRAINT \`FK_d95435c3de3a663682fa21ebc23\` FOREIGN KEY (\`department_id\`) REFERENCES \`departments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batter_stats\` ADD CONSTRAINT \`FK_673bbc97c1577000b37840d4e1e\` FOREIGN KEY (\`player_tournament_id\`) REFERENCES \`player_tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pitcher_stats\` ADD CONSTRAINT \`FK_44266091b556e03d241ace53da0\` FOREIGN KEY (\`player_tournament_id\`) REFERENCES \`player_tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sessions\` ADD CONSTRAINT \`FK_57de40bc620f456c7311aa3a1e6\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`runner_events\` ADD CONSTRAINT \`FK_59adfc26d4958ba0a1f8bd08849\` FOREIGN KEY (\`game_id\`) REFERENCES \`games\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`runner_events\` ADD CONSTRAINT \`FK_29ed21b50d29b0627d007fbac6c\` FOREIGN KEY (\`play_id\`) REFERENCES \`plays\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`runner_events\` ADD CONSTRAINT \`FK_767c5bc5e6b54b9ad7b7569526a\` FOREIGN KEY (\`runner_gp_id\`) REFERENCES \`batter_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`runner_events\` ADD CONSTRAINT \`FK_b31c667c86e6af25392aeb7bbb6\` FOREIGN KEY (\`rbi_batter_gp_id\`) REFERENCES \`batter_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`plays\` ADD CONSTRAINT \`FK_05ecc278ef6219afcf59347a543\` FOREIGN KEY (\`game_id\`) REFERENCES \`games\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`plays\` ADD CONSTRAINT \`FK_ee54c0bd8cc99751aa38be798b4\` FOREIGN KEY (\`game_inning_stat_id\`) REFERENCES \`game_inning_stats\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`plays\` ADD CONSTRAINT \`FK_f447505ff7bf84e808b302d1ce7\` FOREIGN KEY (\`batter_gp_id\`) REFERENCES \`batter_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`plays\` ADD CONSTRAINT \`FK_8bedafb77b3b33f233e5cfde092\` FOREIGN KEY (\`pitcher_gp_id\`) REFERENCES \`pitcher_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`runner\` ADD CONSTRAINT \`FK_137287a68699d56d7c2ab369daa\` FOREIGN KEY (\`runnerGpId\`) REFERENCES \`batter_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`runner\` ADD CONSTRAINT \`FK_58e3b2068aaa4d74ec081daec3e\` FOREIGN KEY (\`responsiblePitcherGpId\`) REFERENCES \`batter_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`runner\` ADD CONSTRAINT \`FK_8b9c7b05d9891ebd54e07703b87\` FOREIGN KEY (\`originPlayId\`) REFERENCES \`plays\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`runner\` DROP FOREIGN KEY \`FK_8b9c7b05d9891ebd54e07703b87\``);
        await queryRunner.query(`ALTER TABLE \`runner\` DROP FOREIGN KEY \`FK_58e3b2068aaa4d74ec081daec3e\``);
        await queryRunner.query(`ALTER TABLE \`runner\` DROP FOREIGN KEY \`FK_137287a68699d56d7c2ab369daa\``);
        await queryRunner.query(`ALTER TABLE \`plays\` DROP FOREIGN KEY \`FK_8bedafb77b3b33f233e5cfde092\``);
        await queryRunner.query(`ALTER TABLE \`plays\` DROP FOREIGN KEY \`FK_f447505ff7bf84e808b302d1ce7\``);
        await queryRunner.query(`ALTER TABLE \`plays\` DROP FOREIGN KEY \`FK_ee54c0bd8cc99751aa38be798b4\``);
        await queryRunner.query(`ALTER TABLE \`plays\` DROP FOREIGN KEY \`FK_05ecc278ef6219afcf59347a543\``);
        await queryRunner.query(`ALTER TABLE \`runner_events\` DROP FOREIGN KEY \`FK_b31c667c86e6af25392aeb7bbb6\``);
        await queryRunner.query(`ALTER TABLE \`runner_events\` DROP FOREIGN KEY \`FK_767c5bc5e6b54b9ad7b7569526a\``);
        await queryRunner.query(`ALTER TABLE \`runner_events\` DROP FOREIGN KEY \`FK_29ed21b50d29b0627d007fbac6c\``);
        await queryRunner.query(`ALTER TABLE \`runner_events\` DROP FOREIGN KEY \`FK_59adfc26d4958ba0a1f8bd08849\``);
        await queryRunner.query(`ALTER TABLE \`sessions\` DROP FOREIGN KEY \`FK_57de40bc620f456c7311aa3a1e6\``);
        await queryRunner.query(`ALTER TABLE \`pitcher_stats\` DROP FOREIGN KEY \`FK_44266091b556e03d241ace53da0\``);
        await queryRunner.query(`ALTER TABLE \`batter_stats\` DROP FOREIGN KEY \`FK_673bbc97c1577000b37840d4e1e\``);
        await queryRunner.query(`ALTER TABLE \`players\` DROP FOREIGN KEY \`FK_d95435c3de3a663682fa21ebc23\``);
        await queryRunner.query(`ALTER TABLE \`players\` DROP FOREIGN KEY \`FK_a88b3d61091c2a3504e19e616fa\``);
        await queryRunner.query(`ALTER TABLE \`players\` DROP FOREIGN KEY \`FK_ba3575d2fbe71fab7155366235e\``);
        await queryRunner.query(`ALTER TABLE \`departments\` DROP FOREIGN KEY \`FK_031d56f4b0c9492b176cc29d07c\``);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` DROP FOREIGN KEY \`FK_4affd1bc756929948778a93a645\``);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` DROP FOREIGN KEY \`FK_2e9fe9ad3545c10f0e68b23e67a\``);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` DROP FOREIGN KEY \`FK_c0525e576c026928aec2fb95bb5\``);
        await queryRunner.query(`ALTER TABLE \`team_tournaments\` DROP FOREIGN KEY \`FK_ffc945523d3efda71a653a9e261\``);
        await queryRunner.query(`ALTER TABLE \`team_tournaments\` DROP FOREIGN KEY \`FK_0843a2f852f36e58beff26c7087\``);
        await queryRunner.query(`ALTER TABLE \`team_tournaments\` DROP FOREIGN KEY \`FK_f95b4d911f29f91a7df914f7cf5\``);
        await queryRunner.query(`ALTER TABLE \`umpire_tournaments\` DROP FOREIGN KEY \`FK_567c84be6fc109ed6426e8f6384\``);
        await queryRunner.query(`ALTER TABLE \`umpire_tournaments\` DROP FOREIGN KEY \`FK_ba4b70070b8d5110132f35de419\``);
        await queryRunner.query(`ALTER TABLE \`umpires\` DROP FOREIGN KEY \`FK_fd8afb174c95560b417d1230136\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_fb2fabf4d3e0529d229b3d215d4\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_9b58bea27187d8b7eb0888ac40f\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_cb2180da34b81b7fd5a44a4e06a\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_7320d78e74745e16633ec876b06\``);
        await queryRunner.query(`ALTER TABLE \`games\` DROP FOREIGN KEY \`FK_231e3bf4d40e033e03864137113\``);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` DROP FOREIGN KEY \`FK_d40a0d4af3721b583167fdeef3c\``);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` DROP FOREIGN KEY \`FK_19742fdd1e5d7b047078be23181\``);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` DROP FOREIGN KEY \`FK_f55dcf4120348b21aa899a00822\``);
        await queryRunner.query(`ALTER TABLE \`game_stats\` DROP FOREIGN KEY \`FK_73309278f6c6b7b7a273c240567\``);
        await queryRunner.query(`ALTER TABLE \`game_stats\` DROP FOREIGN KEY \`FK_13a674c8d1715401b040983dee8\``);
        await queryRunner.query(`ALTER TABLE \`game_stats\` DROP FOREIGN KEY \`FK_207a04127d611441d47686ceeb5\``);
        await queryRunner.query(`ALTER TABLE \`game_stats\` DROP FOREIGN KEY \`FK_bd5db571ec09d387d82d84daf3d\``);
        await queryRunner.query(`ALTER TABLE \`game_stats\` DROP FOREIGN KEY \`FK_a8e2b0df27f8baa40c5aef8d3e3\``);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` DROP FOREIGN KEY \`FK_b1dab303eb41058aff75ce26ace\``);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` DROP FOREIGN KEY \`FK_61a70554b6791a1021a1c80594f\``);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` DROP FOREIGN KEY \`FK_183a7e71b8769c92691056c67b2\``);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_stats\` DROP FOREIGN KEY \`FK_36c2e15af9df5e963ca0ae2135e\``);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` DROP FOREIGN KEY \`FK_f247f29600c4a080125d454072b\``);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` DROP FOREIGN KEY \`FK_16148e5132d3068b00ade5c7827\``);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` DROP FOREIGN KEY \`FK_b29689d47b22e01defb6efd7af3\``);
        await queryRunner.query(`ALTER TABLE \`batter_game_stats\` DROP FOREIGN KEY \`FK_3bd2cb3f2b7140f750a0fdaac8d\``);
        await queryRunner.query(`ALTER TABLE \`virtual_inning_stats\` DROP FOREIGN KEY \`FK_bcb6efe098d74ce92775eb8c9f0\``);
        await queryRunner.query(`ALTER TABLE \`game_inning_stats\` DROP FOREIGN KEY \`FK_f6c3223e06f14dd26279cf9824c\``);
        await queryRunner.query(`ALTER TABLE \`user_profiles\` DROP FOREIGN KEY \`FK_8481388d6325e752cd4d7e26c6d\``);
        await queryRunner.query(`DROP INDEX \`IDX_f5ab3feef948b23b5ab100becd\` ON \`game_roasters\``);
        await queryRunner.query(`DROP INDEX \`IDX_19742fdd1e5d7b047078be2318\` ON \`game_roasters\``);
        await queryRunner.query(`DROP INDEX \`IDX_61a70554b6791a1021a1c80594\` ON \`pitcher_game_participations\``);
        await queryRunner.query(`DROP INDEX \`IDX_16148e5132d3068b00ade5c782\` ON \`batter_game_participations\``);
        await queryRunner.query(`ALTER TABLE \`runner_events\` DROP COLUMN \`end_base\``);
        await queryRunner.query(`ALTER TABLE \`runner_events\` ADD \`end_base\` char NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`runner_events\` DROP COLUMN \`start_base\``);
        await queryRunner.query(`ALTER TABLE \`runner_events\` ADD \`start_base\` char NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`password_reset_tokens\` DROP COLUMN \`token_hash\``);
        await queryRunner.query(`ALTER TABLE \`password_reset_tokens\` ADD \`token_hash\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`email_codes\` DROP COLUMN \`code_hash\``);
        await queryRunner.query(`ALTER TABLE \`email_codes\` ADD \`code_hash\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` DROP COLUMN \`backNumber\``);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` ADD \`backNumber\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` CHANGE \`team_tournament_id\` \`team_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` CHANGE \`team_tournament_id\` \`team_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` CHANGE \`team_tournament_id\` \`team_id\` int NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_e087b4110e44a0d42a4c8a3749\` ON \`game_roasters\` (\`game_id\`, \`team_id\`, \`player_tournament_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_0ab4fa69ea5db41cf49ccbb9d2\` ON \`game_roasters\` (\`team_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_61a0c2f525649b1e1772df22bb\` ON \`pitcher_game_participations\` (\`team_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_a7ccc1dd62d56aac8100c4c6ba\` ON \`batter_game_participations\` (\`team_id\`)`);
        await queryRunner.query(`ALTER TABLE \`runner\` ADD CONSTRAINT \`FK_8b9c7b05d9891ebd54e07703b87\` FOREIGN KEY (\`originPlayId\`) REFERENCES \`snubaseballtracker\`.\`plays\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`runner\` ADD CONSTRAINT \`FK_58e3b2068aaa4d74ec081daec3e\` FOREIGN KEY (\`responsiblePitcherGpId\`) REFERENCES \`snubaseballtracker\`.\`batter_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`runner\` ADD CONSTRAINT \`FK_137287a68699d56d7c2ab369daa\` FOREIGN KEY (\`runnerGpId\`) REFERENCES \`snubaseballtracker\`.\`batter_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`plays\` ADD CONSTRAINT \`FK_f447505ff7bf84e808b302d1ce7\` FOREIGN KEY (\`batter_gp_id\`) REFERENCES \`snubaseballtracker\`.\`batter_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`plays\` ADD CONSTRAINT \`FK_ee54c0bd8cc99751aa38be798b4\` FOREIGN KEY (\`game_inning_stat_id\`) REFERENCES \`snubaseballtracker\`.\`game_inning_stats\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`plays\` ADD CONSTRAINT \`FK_8bedafb77b3b33f233e5cfde092\` FOREIGN KEY (\`pitcher_gp_id\`) REFERENCES \`snubaseballtracker\`.\`pitcher_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`plays\` ADD CONSTRAINT \`FK_05ecc278ef6219afcf59347a543\` FOREIGN KEY (\`game_id\`) REFERENCES \`snubaseballtracker\`.\`games\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`runner_events\` ADD CONSTRAINT \`FK_b31c667c86e6af25392aeb7bbb6\` FOREIGN KEY (\`rbi_batter_gp_id\`) REFERENCES \`snubaseballtracker\`.\`batter_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`runner_events\` ADD CONSTRAINT \`FK_767c5bc5e6b54b9ad7b7569526a\` FOREIGN KEY (\`runner_gp_id\`) REFERENCES \`snubaseballtracker\`.\`batter_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`runner_events\` ADD CONSTRAINT \`FK_59adfc26d4958ba0a1f8bd08849\` FOREIGN KEY (\`game_id\`) REFERENCES \`snubaseballtracker\`.\`games\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`runner_events\` ADD CONSTRAINT \`FK_29ed21b50d29b0627d007fbac6c\` FOREIGN KEY (\`play_id\`) REFERENCES \`snubaseballtracker\`.\`plays\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sessions\` ADD CONSTRAINT \`FK_57de40bc620f456c7311aa3a1e6\` FOREIGN KEY (\`userId\`) REFERENCES \`snubaseballtracker\`.\`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pitcher_stats\` ADD CONSTRAINT \`FK_44266091b556e03d241ace53da0\` FOREIGN KEY (\`player_tournament_id\`) REFERENCES \`snubaseballtracker\`.\`player_tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batter_stats\` ADD CONSTRAINT \`FK_673bbc97c1577000b37840d4e1e\` FOREIGN KEY (\`player_tournament_id\`) REFERENCES \`snubaseballtracker\`.\`player_tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`players\` ADD CONSTRAINT \`FK_d95435c3de3a663682fa21ebc23\` FOREIGN KEY (\`department_id\`) REFERENCES \`snubaseballtracker\`.\`departments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`players\` ADD CONSTRAINT \`FK_ba3575d2fbe71fab7155366235e\` FOREIGN KEY (\`user_id\`) REFERENCES \`snubaseballtracker\`.\`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`players\` ADD CONSTRAINT \`FK_a88b3d61091c2a3504e19e616fa\` FOREIGN KEY (\`college_id\`) REFERENCES \`snubaseballtracker\`.\`colleges\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`departments\` ADD CONSTRAINT \`FK_031d56f4b0c9492b176cc29d07c\` FOREIGN KEY (\`collegeId\`) REFERENCES \`snubaseballtracker\`.\`colleges\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` ADD CONSTRAINT \`FK_c0525e576c026928aec2fb95bb5\` FOREIGN KEY (\`player_id\`) REFERENCES \`snubaseballtracker\`.\`players\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` ADD CONSTRAINT \`FK_4affd1bc756929948778a93a645\` FOREIGN KEY (\`claim_user_id\`) REFERENCES \`snubaseballtracker\`.\`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`player_tournaments\` ADD CONSTRAINT \`FK_2e9fe9ad3545c10f0e68b23e67a\` FOREIGN KEY (\`team_tournament_id\`) REFERENCES \`snubaseballtracker\`.\`team_tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team_tournaments\` ADD CONSTRAINT \`FK_ffc945523d3efda71a653a9e261\` FOREIGN KEY (\`representative_user_id\`) REFERENCES \`snubaseballtracker\`.\`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team_tournaments\` ADD CONSTRAINT \`FK_f95b4d911f29f91a7df914f7cf5\` FOREIGN KEY (\`team_id\`) REFERENCES \`snubaseballtracker\`.\`teams\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team_tournaments\` ADD CONSTRAINT \`FK_0843a2f852f36e58beff26c7087\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`snubaseballtracker\`.\`tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`umpire_tournaments\` ADD CONSTRAINT \`FK_ba4b70070b8d5110132f35de419\` FOREIGN KEY (\`umpire_id\`) REFERENCES \`snubaseballtracker\`.\`umpires\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`umpire_tournaments\` ADD CONSTRAINT \`FK_567c84be6fc109ed6426e8f6384\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`snubaseballtracker\`.\`tournaments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`umpires\` ADD CONSTRAINT \`FK_fd8afb174c95560b417d1230136\` FOREIGN KEY (\`user_id\`) REFERENCES \`snubaseballtracker\`.\`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_fb2fabf4d3e0529d229b3d215d4\` FOREIGN KEY (\`record_umpire_id\`) REFERENCES \`snubaseballtracker\`.\`umpires\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_cb2180da34b81b7fd5a44a4e06a\` FOREIGN KEY (\`away_team_tournament_id\`) REFERENCES \`snubaseballtracker\`.\`team_tournaments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_9b58bea27187d8b7eb0888ac40f\` FOREIGN KEY (\`winner_team_tournament_id\`) REFERENCES \`snubaseballtracker\`.\`team_tournaments\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_7320d78e74745e16633ec876b06\` FOREIGN KEY (\`home_team_tournament_id\`) REFERENCES \`snubaseballtracker\`.\`team_tournaments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`games\` ADD CONSTRAINT \`FK_231e3bf4d40e033e03864137113\` FOREIGN KEY (\`tournament_id\`) REFERENCES \`snubaseballtracker\`.\`tournaments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` ADD CONSTRAINT \`FK_f55dcf4120348b21aa899a00822\` FOREIGN KEY (\`game_id\`) REFERENCES \`snubaseballtracker\`.\`games\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` ADD CONSTRAINT \`FK_d40a0d4af3721b583167fdeef3c\` FOREIGN KEY (\`player_tournament_id\`) REFERENCES \`snubaseballtracker\`.\`player_tournaments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_roasters\` ADD CONSTRAINT \`FK_0ab4fa69ea5db41cf49ccbb9d2a\` FOREIGN KEY (\`team_id\`) REFERENCES \`snubaseballtracker\`.\`teams\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_stats\` ADD CONSTRAINT \`FK_bd5db571ec09d387d82d84daf3d\` FOREIGN KEY (\`home_pitcher_participation_id\`) REFERENCES \`snubaseballtracker\`.\`pitcher_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_stats\` ADD CONSTRAINT \`FK_a8e2b0df27f8baa40c5aef8d3e3\` FOREIGN KEY (\`game_id\`) REFERENCES \`snubaseballtracker\`.\`games\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_stats\` ADD CONSTRAINT \`FK_73309278f6c6b7b7a273c240567\` FOREIGN KEY (\`away_batter_participation_id\`) REFERENCES \`snubaseballtracker\`.\`batter_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_stats\` ADD CONSTRAINT \`FK_207a04127d611441d47686ceeb5\` FOREIGN KEY (\`home_batter_participation_id\`) REFERENCES \`snubaseballtracker\`.\`batter_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`game_stats\` ADD CONSTRAINT \`FK_13a674c8d1715401b040983dee8\` FOREIGN KEY (\`away_pitcher_participation_id\`) REFERENCES \`snubaseballtracker\`.\`pitcher_game_participations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` ADD CONSTRAINT \`FK_b1dab303eb41058aff75ce26ace\` FOREIGN KEY (\`player_tournament_id\`) REFERENCES \`snubaseballtracker\`.\`player_tournaments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` ADD CONSTRAINT \`FK_61a0c2f525649b1e1772df22bb2\` FOREIGN KEY (\`team_id\`) REFERENCES \`snubaseballtracker\`.\`teams\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_participations\` ADD CONSTRAINT \`FK_183a7e71b8769c92691056c67b2\` FOREIGN KEY (\`game_id\`) REFERENCES \`snubaseballtracker\`.\`games\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pitcher_game_stats\` ADD CONSTRAINT \`FK_36c2e15af9df5e963ca0ae2135e\` FOREIGN KEY (\`pitcher_game_participation_id\`) REFERENCES \`snubaseballtracker\`.\`pitcher_game_participations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` ADD CONSTRAINT \`FK_f247f29600c4a080125d454072b\` FOREIGN KEY (\`player_tournament_id\`) REFERENCES \`snubaseballtracker\`.\`player_tournaments\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` ADD CONSTRAINT \`FK_b29689d47b22e01defb6efd7af3\` FOREIGN KEY (\`game_id\`) REFERENCES \`snubaseballtracker\`.\`games\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batter_game_participations\` ADD CONSTRAINT \`FK_a7ccc1dd62d56aac8100c4c6ba6\` FOREIGN KEY (\`team_id\`) REFERENCES \`snubaseballtracker\`.\`teams\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batter_game_stats\` ADD CONSTRAINT \`FK_3bd2cb3f2b7140f750a0fdaac8d\` FOREIGN KEY (\`batter_game_participation_id\`) REFERENCES \`snubaseballtracker\`.\`batter_game_participations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`virtual_inning_stats\` ADD CONSTRAINT \`FK_bcb6efe098d74ce92775eb8c9f0\` FOREIGN KEY (\`game_id\`) REFERENCES \`snubaseballtracker\`.\`games\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`game_inning_stats\` ADD CONSTRAINT \`FK_f6c3223e06f14dd26279cf9824c\` FOREIGN KEY (\`game_id\`) REFERENCES \`snubaseballtracker\`.\`games\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_profiles\` ADD CONSTRAINT \`FK_8481388d6325e752cd4d7e26c6d\` FOREIGN KEY (\`userId\`) REFERENCES \`snubaseballtracker\`.\`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
